version: "3.7"

services:
#  backend:
#    container_name: backend
#    build: .
#    ports:
#      - 8888:8080
#    environment:
#      - DB_HOST=postgres
#      - DB_USERNAME=user
#      - DB_PASSWORD=password

  postgres:
    image: postgres:11
    ports:
      - 5432:5432
    volumes:
      - ./db/seed.sql:/docker-entrypoint-initdb.d/seed.sql
    environment:
      - POSTGRES_DB=shopping
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
  redis:
    image: redis
    ports:
      - 6379:6379
